import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Header } from '../components/Header'
import { HomePage } from './HomePage'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <HomePage />
    </div>
  )
}

export async function getFilms(){
    const request = await fetch(`https://www.swapi.tech/api/films`)
        .then((res) => res.json())

        console.log(request)
}
